/**
 * Setup Step: Complete
 * ─────────────────────
 * Shows the generated .env.local file for the user to copy,
 * along with clear next steps to finish setup.
 */

"use client";

import { useState } from "react";
import {
  PartyPopper,
  Copy,
  Check,
  Terminal,
  Globe,
  Rocket,
  ShieldCheck,
  User,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { SetupData } from "@/app/setup/page";

interface StepCompleteProps {
  data: SetupData;
}

/**
 * Generate the .env.local file contents from the collected data.
 */
function generateEnvFile(data: SetupData): string {
  // Generate a random NEXTAUTH_SECRET
  const randomSecret =
    typeof window !== "undefined"
      ? btoa(
          Array.from(crypto.getRandomValues(new Uint8Array(32)))
            .map((b) => String.fromCharCode(b))
            .join("")
        )
      : "change-me-to-a-random-secret";

  return `# ============================================
# ${data.appName.toUpperCase()} - Environment Variables
# Generated by Infinity Core Setup Wizard
# ============================================

# ── App Configuration ──────────────────────────
NEXT_PUBLIC_APP_URL=${data.appUrl}

# ── Supabase ──────────────────────────────────
NEXT_PUBLIC_SUPABASE_URL=${data.supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${data.supabaseAnonKey}
SUPABASE_SERVICE_ROLE_KEY=${data.supabaseServiceRoleKey}
DATABASE_URL=${data.databaseUrl}

# ── Stripe (Optional — add when ready for payments) ──
# Get keys from: dashboard.stripe.com → Developers → API keys
# For local webhooks: npm run stripe:listen
STRIPE_SECRET_KEY=${data.stripeSecretKey || ""}
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${data.stripePublishableKey || ""}
STRIPE_WEBHOOK_SECRET=${data.stripeWebhookSecret || ""}

# ── Resend (Optional — add when ready for emails) ──
# Get from: resend.com → API Keys
RESEND_API_KEY=${data.resendApiKey || ""}
RESEND_FROM_EMAIL=${data.resendFromEmail || ""}

# ── NextAuth ──────────────────────────────────
NEXTAUTH_SECRET=${randomSecret}
NEXTAUTH_URL=${data.appUrl}

# ── OAuth Providers (Optional — add later) ────
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
`;
}

export function StepComplete({ data }: StepCompleteProps) {
  const [copied, setCopied] = useState(false);
  const envContent = generateEnvFile(data);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(envContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  const nextSteps = [
    {
      icon: Copy,
      title: "1. Save your .env.local",
      description:
        'Copy the configuration below and paste it into the .env.local file in your project root. Replace the existing contents entirely.',
    },
    {
      icon: Terminal,
      title: "2. Set up the database & test accounts",
      description:
        "Run the following commands in your terminal to create the database tables, seed initial data, and create test accounts:",
      code: "npx prisma db push && npm run db:seed",
    },
    {
      icon: Globe,
      title: "3. Restart the dev server",
      description:
        "Stop the current server (Ctrl+C) and restart it. The app will detect the new config and load normally.",
      code: "npm run dev",
    },
    {
      icon: Rocket,
      title: "4. You're live!",
      description:
        "Open http://localhost:3000 and log in with the test accounts below. No email verification needed.",
    },
  ];

  return (
    <div className="space-y-8">
      {/* Success header */}
      <div className="text-center space-y-4">
        <div className="inline-flex items-center justify-center h-16 w-16 rounded-2xl bg-emerald-100 dark:bg-emerald-900/30 mx-auto">
          <PartyPopper className="h-8 w-8 text-emerald-600" />
        </div>
        <h1 className="text-3xl font-bold tracking-tight">
          Setup Complete!
        </h1>
        <p className="text-lg text-muted-foreground max-w-xl mx-auto">
          Your configuration is ready. Follow the steps below to finish setting
          up <strong>{data.appName}</strong>.
        </p>
      </div>

      {/* Generated .env.local */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-base">
                Your .env.local Configuration
              </CardTitle>
              <CardDescription>
                Copy this entire block and paste it into your .env.local file.
              </CardDescription>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="shrink-0"
            >
              {copied ? (
                <>
                  <Check className="mr-2 h-3 w-3 text-emerald-600" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="mr-2 h-3 w-3" />
                  Copy
                </>
              )}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <pre className="max-h-64 overflow-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-300 font-mono leading-relaxed">
            {envContent}
          </pre>
        </CardContent>
      </Card>

      {/* Next steps */}
      <div className="space-y-4">
        <h2 className="text-lg font-semibold">Next Steps</h2>
        {nextSteps.map((step) => (
          <Card key={step.title}>
            <CardContent className="flex items-start gap-4 p-4">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 mt-0.5">
                <step.icon className="h-5 w-5 text-primary" />
              </div>
              <div className="space-y-1.5">
                <h3 className="font-medium text-sm">{step.title}</h3>
                <p className="text-sm text-muted-foreground">
                  {step.description}
                </p>
                {step.code && (
                  <pre className="rounded-md bg-slate-950 px-3 py-2 text-xs text-emerald-400 font-mono mt-2">
                    {step.code}
                  </pre>
                )}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Test Account Credentials */}
      <Card className="border-amber-200 dark:border-amber-800 bg-amber-50/50 dark:bg-amber-950/20">
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <ShieldCheck className="h-5 w-5 text-amber-600" />
            Test Account Credentials
          </CardTitle>
          <CardDescription>
            These accounts are auto-created when you run <code className="text-xs bg-slate-200 dark:bg-slate-800 px-1 py-0.5 rounded">npm run db:seed</code>.
            No email verification required.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="flex items-start gap-3 rounded-lg border border-amber-200 dark:border-amber-800 bg-white dark:bg-slate-950 p-3">
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-red-100 dark:bg-red-900/30">
              <ShieldCheck className="h-4 w-4 text-red-600" />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2">
                <p className="font-medium text-sm">Admin Account</p>
                <span className="text-[10px] font-medium px-1.5 py-0.5 rounded bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400">
                  ADMIN
                </span>
              </div>
              <div className="mt-1 font-mono text-xs text-muted-foreground">
                <span className="text-foreground">admin@test.com</span>
                {" / "}
                <span className="text-foreground">Admin123!</span>
              </div>
              <p className="text-[11px] text-muted-foreground mt-1">
                Full access: dashboard, admin panel, user management, Pro plan
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3 rounded-lg border border-amber-200 dark:border-amber-800 bg-white dark:bg-slate-950 p-3">
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-blue-100 dark:bg-blue-900/30">
              <User className="h-4 w-4 text-blue-600" />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2">
                <p className="font-medium text-sm">User Account</p>
                <span className="text-[10px] font-medium px-1.5 py-0.5 rounded bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">
                  USER
                </span>
              </div>
              <div className="mt-1 font-mono text-xs text-muted-foreground">
                <span className="text-foreground">user@test.com</span>
                {" / "}
                <span className="text-foreground">User123!</span>
              </div>
              <p className="text-[11px] text-muted-foreground mt-1">
                Standard access: dashboard, projects, billing, Free plan
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
