/**
 * Setup Step: Complete
 * ─────────────────────
 * Shows the generated .env.local file for the user to copy,
 * along with clear next steps to finish setup.
 */

"use client";

import { useState } from "react";
import {
  PartyPopper,
  Copy,
  Check,
  Terminal,
  Globe,
  Rocket,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { SetupData } from "@/app/setup/page";

interface StepCompleteProps {
  data: SetupData;
}

/**
 * Generate the .env.local file contents from the collected data.
 */
function generateEnvFile(data: SetupData): string {
  // Generate a random NEXTAUTH_SECRET
  const randomSecret =
    typeof window !== "undefined"
      ? btoa(
          Array.from(crypto.getRandomValues(new Uint8Array(32)))
            .map((b) => String.fromCharCode(b))
            .join("")
        )
      : "change-me-to-a-random-secret";

  return `# ============================================
# ${data.appName.toUpperCase()} - Environment Variables
# Generated by Infinity Core Setup Wizard
# ============================================

# ── App Configuration ──────────────────────────
NEXT_PUBLIC_APP_URL=${data.appUrl}

# ── Supabase ──────────────────────────────────
NEXT_PUBLIC_SUPABASE_URL=${data.supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${data.supabaseAnonKey}
SUPABASE_SERVICE_ROLE_KEY=${data.supabaseServiceRoleKey}
DATABASE_URL=${data.databaseUrl}

# ── Stripe ────────────────────────────────────
STRIPE_SECRET_KEY=${data.stripeSecretKey}
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${data.stripePublishableKey}
STRIPE_WEBHOOK_SECRET=${data.stripeWebhookSecret}

# ── Resend (Email) ────────────────────────────
RESEND_API_KEY=${data.resendApiKey}
RESEND_FROM_EMAIL=${data.resendFromEmail}

# ── NextAuth ──────────────────────────────────
NEXTAUTH_SECRET=${randomSecret}
NEXTAUTH_URL=${data.appUrl}

# ── OAuth Providers (Optional — add later) ────
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
`;
}

export function StepComplete({ data }: StepCompleteProps) {
  const [copied, setCopied] = useState(false);
  const envContent = generateEnvFile(data);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(envContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  const nextSteps = [
    {
      icon: Copy,
      title: "1. Save your .env.local",
      description:
        'Copy the configuration below and paste it into the .env.local file in your project root. Replace the existing contents entirely.',
    },
    {
      icon: Terminal,
      title: "2. Set up the database",
      description:
        "Run the following commands in your terminal to create the database tables and seed initial data:",
      code: "npx prisma db push && npm run db:seed",
    },
    {
      icon: Globe,
      title: "3. Restart the dev server",
      description:
        "Stop the current server (Ctrl+C) and restart it. The app will detect the new config and load normally.",
      code: "npm run dev",
    },
    {
      icon: Rocket,
      title: "4. You're live!",
      description:
        "Open http://localhost:3000 in your browser. You should see the landing page. Sign up for an account to test the full flow.",
    },
  ];

  return (
    <div className="space-y-8">
      {/* Success header */}
      <div className="text-center space-y-4">
        <div className="inline-flex items-center justify-center h-16 w-16 rounded-2xl bg-emerald-100 dark:bg-emerald-900/30 mx-auto">
          <PartyPopper className="h-8 w-8 text-emerald-600" />
        </div>
        <h1 className="text-3xl font-bold tracking-tight">
          Setup Complete!
        </h1>
        <p className="text-lg text-muted-foreground max-w-xl mx-auto">
          Your configuration is ready. Follow the steps below to finish setting
          up <strong>{data.appName}</strong>.
        </p>
      </div>

      {/* Generated .env.local */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-base">
                Your .env.local Configuration
              </CardTitle>
              <CardDescription>
                Copy this entire block and paste it into your .env.local file.
              </CardDescription>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="shrink-0"
            >
              {copied ? (
                <>
                  <Check className="mr-2 h-3 w-3 text-emerald-600" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="mr-2 h-3 w-3" />
                  Copy
                </>
              )}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <pre className="max-h-64 overflow-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-300 font-mono leading-relaxed">
            {envContent}
          </pre>
        </CardContent>
      </Card>

      {/* Next steps */}
      <div className="space-y-4">
        <h2 className="text-lg font-semibold">Next Steps</h2>
        {nextSteps.map((step) => (
          <Card key={step.title}>
            <CardContent className="flex items-start gap-4 p-4">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 mt-0.5">
                <step.icon className="h-5 w-5 text-primary" />
              </div>
              <div className="space-y-1.5">
                <h3 className="font-medium text-sm">{step.title}</h3>
                <p className="text-sm text-muted-foreground">
                  {step.description}
                </p>
                {step.code && (
                  <pre className="rounded-md bg-slate-950 px-3 py-2 text-xs text-emerald-400 font-mono mt-2">
                    {step.code}
                  </pre>
                )}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
